### PR TITLE
Switch to the MIT license

### PR DESCRIPTION
**Pull request by busimus**
I received a request (see #10) to change the GPLv3 license of the project to a less restrictive one. 

I never liked GPLv3 but was forced into licensing the project under it due to having a dependency on a GPLv3 library (PyQt5). After PySide2 (an alternative to PyQt5 that is LGPL licensed) became stable, I changed the code to work with the QtPy abstraction layer that allows the program to run against PyQt5 or PySide2, chosen at runtime. Now there's no legal requirement for the project to be under GPLv3 – a non-GPL program can use an LGPL library with no legal issues.

So I'd like change the project's license to [MIT](https://en.wikipedia.org/wiki/MIT_License). In order to do that every contributor must agree to relicense their contributions under the new terms. See the contents of the pull request for the full scope of the changes. It will be merged as soon as everyone agrees.

List of contributors who currently agree to the new terms:
* [X] Alexander Bus (@busimus)
* [X] Thomas Hess (@luziferius)
* [ ] Anil Berry (@aberrya)

**Please state whether you agree or disagree to relicense the project in the comments to this pull request** (or through other ways of contacting me which you can find in my profile). If you have any concerns, you're free to voice them as well.

Thanks.

### CODE REVIEW

**Comment by luziferius** [comment]
If you wish to switch to MIT, I'm fine with the change.

Should I create a GPG signed empty commit to put the consent into the git history (via commit message)? Then I'll create a pull request against this branch.

**Comment by busimus** [comment]
Sure, go ahead. Your previous commits were signed, so that would be the proper way to do this.

**Comment by busimus** [comment]
Alright, it's been a week. In the interest of this process not taking forever, I'll ping everyone again. 

@aberrya @luziferius

**Comment by luziferius** [comment]
Ok, done from my side. https://github.com/busimus/cutelog/pull/12

But don’t _squash_ this PR on merge, as that’ll kill the GPG signatures.

**Comment by aberrya** [comment]
I agree to change the project's license to MIT.

**Pull request merged**
